title: NLU/CompSem
description: The syllabus for the course Natural Language Understanding and Computational Semantics (DS-GA/LING-GA 1012) at New York University
author: Sophie Hao
baseurl: '/syllabus'
url: 'https://nyu-dsga1012-s24.github.io/' 
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]

nav_external_links:
  - title: Brightspace (Unused)
    url: https://brightspace.nyu.edu/
    hide_icon: false
  - title: Gradescope (Feedback)
    url: https://www.gradescope.com/
    hide_icon: false
  - title: Campuswire (Discussion)
    url: https://campuswire.com/c/GE05961C3
    hide_icon: false
  - title: GitHub (Assignments)
    url: https://github.com/nyu-dsga1012-s24
    hide_icon: false


# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.7.0
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty
footer_content:

# Collections for website data
collections:
  modules:
  announcements:

# Default layouts for each collection type
defaults:
  - scope:
      path: ''
      type: modules
    values:
      layout: module
  - scope:
      path: ''
      type: announcements
    values:
      layout: announcement

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
